// 금융상품 카탈로그 — 백엔드에 상품 데이터가 생기면 /api/products 로 대체 가능.
// interest/debt/credit 기본값은 데모용(백엔드 미제공), cash(월 현금흐름)는 진단 순수익으로 대체된다.
export const BASE = { cash: 182, interest: 12.0, debt: 38, credit: 742 };

export const PRODUCTS = [
  { id: 'op', name: 'KB 소상공인 든든 운영자금 대출', short: '든든 운영자금 대출', tag: '운영자금 대출',
    icon: '₩', iconBg: '#FFF1CC', iconColor: '#C98A00', tagBg: '#FFF1CC', tagColor: '#C98A00', fit: 94,
    reason: '매출 대비 현금 여유가 빠듯한 달이 있어요. 한도 내에서 필요한 만큼만 쓰는 운영자금이 잘 맞아요.',
    spec1: '한도 최대 5,000만원', spec2: '금리 연 4.8%~',
    eff: { cash: 34, interest: 6.2, debt: 9, credit: -8 },
    effectText: '월 현금흐름이 +34만원 여유로워지지만, 이자 부담이 월 6.2만원 늘고 부채비율이 9%p 올라요.',
    link: 'https://obank.kbstar.com/quics?page=C016613',
    details: [
      { k: '대상', v: '업력 1년 이상 개인사업자' },
      { k: '상환 방식', v: '한도대출(마이너스 통장식) 또는 원리금 균등' },
      { k: '우대 조건', v: 'KB 주거래 실적 시 최대 0.6%p 금리 우대' },
    ] },
  { id: 'policy', name: '서울신보 보증부 정책자금 대출', short: '보증부 정책자금', tag: '정책자금 대출',
    icon: '◆', iconBg: '#E4EEF9', iconColor: '#4A79B8', tagBg: '#E4EEF9', tagColor: '#4A79B8', fit: 91,
    reason: '서울신용보증재단 보증으로 낮은 금리에 이용할 수 있어요. 상위 25% 이내 사장님은 우대 대상이에요.',
    spec1: '한도 최대 3,000만원', spec2: '금리 연 2.9% 고정',
    eff: { cash: 28, interest: 2.1, debt: 7, credit: -3 },
    effectText: '낮은 고정금리라 이자 부담은 월 2.1만원만 늘어요. 현금흐름은 +28만원 개선돼요.',
    link: 'https://obank.kbstar.com/quics?page=C016613',
    details: [
      { k: '대상', v: '서울시 소재 소상공인, 보증심사 통과 시' },
      { k: '상환 방식', v: '1년 거치 4년 분할상환' },
      { k: '우대 조건', v: '상위 25% 이내 우수 점포 보증료 50% 감면' },
    ] },
  { id: 'refi', name: '소상공인 저금리 대환대출', short: '저금리 대환대출', tag: '정책자금 대출',
    icon: '⇄', iconBg: '#E4EEF9', iconColor: '#4A79B8', tagBg: '#E4EEF9', tagColor: '#4A79B8', fit: 88,
    reason: '기존 고금리 대출을 갈아타면 이자 부담을 크게 줄일 수 있어요.',
    spec1: '기존 대출 대환 전용', spec2: '금리 연 4.0% 이하',
    eff: { cash: 8, interest: -8.4, debt: -4, credit: 15 },
    effectText: '이자 부담이 월 8.4만원 줄고, 상환 이력이 정리되며 신용점수가 +15점 개선돼요.',
    link: 'https://obank.kbstar.com/quics?page=C016613',
    details: [
      { k: '대상', v: '연 7% 이상 고금리 사업자 대출 보유자' },
      { k: '상환 방식', v: '기존 대출 잔액 범위 내 대환' },
      { k: '우대 조건', v: '성실 상환 6개월 시 추가 금리 인하' },
    ] },
  { id: 'save', name: 'KB 사장님 우대 적금', short: '사장님 우대 적금', tag: '예·적금',
    icon: '★', iconBg: '#EDF5E1', iconColor: '#7FA95E', tagBg: '#EDF5E1', tagColor: '#5E8A3E', fit: 82,
    reason: '매출이 안정적인 사장님께는 비상금 적립이 먼저예요. 사업자 우대금리를 드려요.',
    spec1: '월 10~50만원', spec2: '금리 연 4.2% 우대',
    eff: { cash: -30, interest: 0, debt: 0, credit: 12 },
    effectText: '월 30만원이 적립으로 나가지만, 꾸준한 금융 거래 실적으로 신용점수가 +12점 개선돼요.',
    link: 'https://obank.kbstar.com/quics?page=C016613',
    details: [
      { k: '대상', v: '개인사업자 대표 누구나' },
      { k: '기간', v: '12~36개월 자유 선택' },
      { k: '우대 조건', v: '사업자 계좌 자동이체 시 +0.5%p' },
    ] },
  { id: 'gov', name: '노란우산공제 (정부 지원)', short: '노란우산공제', tag: '정부 지원제도',
    icon: '☂', iconBg: '#FFF0E4', iconColor: '#D07A3A', tagBg: '#FFF0E4', tagColor: '#C06A2A', fit: 79,
    reason: '폐업·노후 대비 공제로, 납입액 전액 소득공제 혜택이 있어요.',
    spec1: '월 5~100만원', spec2: '소득공제 최대 600만원',
    eff: { cash: -10, interest: 0, debt: 0, credit: 5 },
    effectText: '월 10만원 납입으로 소득공제 혜택을 받고, 성실 납입 실적이 신용에 +5점 반영돼요.',
    link: 'https://obank.kbstar.com/quics?page=C016613',
    details: [
      { k: '대상', v: '소기업·소상공인 대표' },
      { k: '혜택', v: '납입액 전액 소득공제(최대 600만원), 압류 불가 자산' },
      { k: '가입 방법', v: 'KB스타뱅킹에서 대행 가입 가능' },
    ] },
  { id: 'ins', name: 'KB 화재·배상책임 보험', short: '화재·배상 보험', tag: '보험',
    icon: '✚', iconBg: '#FDE8E6', iconColor: '#D0564C', tagBg: '#FDE8E6', tagColor: '#C0463C', fit: 76,
    reason: '점포 화재·고객 배상사고는 한 번에 큰 손실로 이어져요. 월 커피 한 잔 값으로 대비해요.',
    spec1: '월 보험료 4.5만원', spec2: '보장 최대 1억원',
    eff: { cash: -4.5, interest: 0, debt: 0, credit: 0 },
    effectText: '월 4.5만원으로 화재·배상 리스크를 최대 1억원까지 보장받아요.',
    link: 'https://obank.kbstar.com/quics?page=C016613',
    details: [
      { k: '보장 범위', v: '화재·폭발 손해, 고객 배상책임 최대 1억원' },
      { k: '기간', v: '1년 갱신형' },
      { k: '우대 조건', v: '무사고 갱신 시 보험료 5% 할인' },
    ] },
];